FROM alpine

RUN apk add --no-cache python3

ADD /Limerick.txt /home/data/Limerick.txt
ADD /IF.txt /home/data/IF.txt
ADD /himakardocker.py /home/himakardocker.py
 RUN mkdir -p /home/output/
CMD ["/home/himakardocker.py"]
ENTRYPOINT ["python3"]